export const checkoutRequests = [
  {
    inventoryRef: {
      id: "inv001",
      name: "Canon EOS R5",
      brand: "Canon",
      category: "Camera",
      status: "Checked In",
    },
    requestedBy: "rahim@smilemkt.com",
    purpose: "Client video shoot",
    neededFrom: "2025-07-16",
    neededTo: "2025-07-20",
    note: "Need 4K lens",
    status: "pending",
    createdAt: "July 25, 2025 at 6:24:37 PM UTC+6",
  },
  {
    inventoryRef: {
      id: "inv002",
      name: "MacBook Pro M2",
      brand: "Apple",
      category: "Laptop",
      status: "Checked Out",
    },
    requestedBy: "salma@smilemkt.com",
    purpose: "Team presentation",
    neededFrom: "2025-07-17",
    neededTo: "2025-07-18",
    note: "HDMI cable also needed",
    status: "approved",
    adminDecisionBy: "admin@smilemkt.com",
    decisionDate: "2025-07-15T14:00:00Z",
    createdAt: "July 25, 2025 at 6:24:37 PM UTC+6",
  },
  {
    inventoryRef: {
      id: "inv004",
      name: "Sony A7 III",
      brand: "Sony",
      category: "Camera",
      status: "Checked In",
    },
    requestedBy: "kamal@smilemkt.com",
    purpose: "Client meeting in Dhaka",
    neededFrom: "2025-07-18",
    neededTo: "2025-07-19",
    note: "Need with tripod",
    status: "rejected",
    adminDecisionBy: "admin@smilemkt.com",
    decisionDate: "2025-07-15T11:40:00Z",
    createdAt: "July 25, 2025 at 6:24:37 PM UTC+6",
  },
  {
    inventoryRef: {
      id: "inv005",
      name: "Godox LED Light",
      brand: "Godox",
      category: "Lighting",
      status: "Checked In",
    },
    requestedBy: "nasrin@smilemkt.com",
    purpose: "Studio lighting test",
    neededFrom: "2025-07-19",
    neededTo: "2025-07-22",
    note: "",
    status: "pending",
    createdAt: "July 25, 2025 at 6:24:37 PM UTC+6",
  },
  {
    inventoryRef: {
      id: "inv007",
      name: "DJI Ronin-S",
      brand: "DJI",
      category: "Stabilizer",
      status: "Checked In",
    },
    requestedBy: "jamil@smilemkt.com",
    purpose: "Outdoor shoot",
    neededFrom: "2025-07-16",
    neededTo: "2025-07-17",
    note: "Raincoat cover requested",
    status: "approved",
    adminDecisionBy: "admin@smilemkt.com",
    decisionDate: "2025-07-15T10:45:00Z",
    createdAt: "July 25, 2025 at 6:24:37 PM UTC+6",
  },
  {
    inventoryRef: {
      id: "inv009",
      name: "Rode VideoMic NTG",
      brand: "Rode",
      category: "Microphone",
      status: "Checked In",
    },
    requestedBy: "mita@smilemkt.com",
    purpose: "Social media content shoot",
    neededFrom: "2025-07-20",
    neededTo: "2025-07-22",
    note: "",
    status: "pending",
    createdAt: "July 25, 2025 at 6:24:37 PM UTC+6",
  },
  {
    inventoryRef: {
      id: "inv006",
      name: "Aputure Softbox Kit",
      brand: "Aputure",
      category: "Lighting",
      status: "Checked Out",
    },
    requestedBy: "fahim@smilemkt.com",
    purpose: "Product photography",
    neededFrom: "2025-07-16",
    neededTo: "2025-07-17",
    note: "Soft light only",
    status: "rejected",
    createdAt: "July 25, 2025 at 6:24:37 PM UTC+6",
  },
  {
    inventoryRef: {
      id: "inv010",
      name: "Logitech StreamCam",
      brand: "Logitech",
      category: "Camera",
      status: "Checked In",
    },
    requestedBy: "farzana@smilemkt.com",
    purpose: "Live webinar",
    neededFrom: "2025-07-17",
    neededTo: "2025-07-17",
    note: "Ethernet cable required",
    status: "approved",
    adminDecisionBy: "admin@smilemkt.com",
    decisionDate: "2025-07-15T13:15:00Z",
    createdAt: "July 25, 2025 at 6:24:37 PM UTC+6",
  },
  {
    inventoryRef: {
      id: "inv003",
      name: "BenQ Projector EX600",
      brand: "BenQ",
      category: "Projector",
      status: "Checked In",
    },
    requestedBy: "anik@smilemkt.com",
    purpose: "Team off-site",
    neededFrom: "2025-07-18",
    neededTo: "2025-07-19",
    note: "",
    status: "pending",
    createdAt: "July 25, 2025 at 6:24:37 PM UTC+6",
  },
  {
    inventoryRef: {
      id: "inv008",
      name: "DJI Mini 3 Pro",
      brand: "DJI",
      category: "Drone",
      status: "Checked In",
    },
    requestedBy: "tamim@smilemkt.com",
    purpose: "Music video shoot",
    neededFrom: "2025-07-21",
    neededTo: "2025-07-24",
    note: "Drone with spare battery",
    status: "pending",
    createdAt: "July 25, 2025 at 6:24:37 PM UTC+6",
  },
];
