export const clientRequestList = [
  {
    clientName: "Emily Johnson",
    clientEmail: "emily.johnson@email.com",
    message: "Hi, I'm interested in renting the DSLR Camera for a 3-day shoot.",
    status: "new",
    handledBy: null,
    createdAt: "2025-07-10T10:25:00Z",
    inventoryRef: {
      id: "dslr_camera_001",
      name: "Canon EOS 90D",
      brand: "Canon",
      category: "Camera",
      status: "Available",
    },
  },
  {
    clientName: "Michael Lee",
    clientEmail: "michael.lee@creativehub.org",
    message:
      "We'd like to inquire about the speaker system for our upcoming event.",
    status: "in_progress",
    handledBy: "Rahim Ahmed",
    createdAt: "2025-07-09T15:47:00Z",
    inventoryRef: {
      id: "speaker_system_002",
      name: "Yamaha StagePas 600BT",
      brand: "Yamaha",
      category: "Sound System",
      status: "Reserved",
    },
  },
  {
    clientName: "Sabrina Ahmed",
    clientEmail: "sabrina@filmcrew.co",
    message:
      "Can you please confirm if the lighting kit is available for rental this weekend?",
    status: "completed",
    handledBy: "Rahim Ahmed",
    createdAt: "2025-07-05T12:03:00Z",
    inventoryRef: {
      id: "lighting_kit_005",
      name: "Godox LED Lighting Kit",
      brand: "Godox",
      category: "Lighting",
      status: "Checked Out",
    },
  },
  {
    clientName: "David Osei",
    clientEmail: "david.osei@techvision.com",
    message: "Looking to buy the used MacBook Pro listed on the client portal.",
    status: "new",
    handledBy: null,
    createdAt: "2025-07-13T09:15:00Z",
    inventoryRef: {
      id: "macbookpro_2020_008",
      name: "MacBook Pro 13-inch 2020",
      brand: "Apple",
      category: "Laptop",
      status: "Available",
    },
  },
  {
    clientName: "Nadia Khan",
    clientEmail: "contact@nadiadesignstudio.com",
    message: "Hello, I’d like to schedule a viewing for the Canon EF Lens Kit.",
    status: "in_progress",
    handledBy: "Sadia Noor",
    createdAt: "2025-07-11T16:42:00Z",
    inventoryRef: {
      id: "canon_lens_kit_014",
      name: "Canon EF 24–70mm Lens Kit",
      brand: "Canon",
      category: "Lens",
      status: "Available",
    },
  },
  {
    clientName: "Michael Lee",
    clientEmail: "michael.lee@creativehub.org",
    message:
      "We'd like to inquire about the speaker system for our upcoming event.",
    status: "in_progress",
    handledBy: "Rahim Ahmed",
    createdAt: "2025-07-09T15:47:00Z",
    inventoryRef: {
      id: "speaker_system_002",
      name: "Yamaha StagePas 600BT",
      brand: "Yamaha",
      category: "Sound System",
      status: "Reserved",
    },
  },
];
