export const inventoryList = [
  {
    id: "inv001",
    name: "MacBook Pro",
    brand: "Apple",
    category: "Laptop",
    serialNumber: "MBP-001",
    location: "IT Desk Room",
    status: "Checked Out",
    stock: 4,
    checkedOutBy: "john doe",
    sellingType: "Purchase",
    price: 1200,
    contactLink: "https://docs.google.com/",
    isVisibleToClients: true,
    tag: ["tech"],
    image: "/images/products/laptop.png",
    createdAt: "2025-07-15T10:00:00Z",
  },
  {
    id: "inv002",
    name: "Projector",
    brand: "Asus",
    category: "Projector",
    serialNumber: "PROJ-002",
    location: "Conference Room",
    status: "Checked Out",
    stock: 8,
    checkedOutBy: "alex root",
    sellingType: "rent",
    price: 600,
    contactLink: "https://docs.google.com/",
    isVisibleToClients: true,
    tag: ["tech"],
    image: "/images/products/projector.png",
    createdAt: "2025-07-15T10:00:00Z",
  },
  {
    id: "inv003",
    name: "Sony Camera",
    brand: "Sony",
    category: "Camera",
    serialNumber: "CAM-003",
    location: "Main Studio",
    status: "Checked In",
    stock: 12,
    checkedOutBy: null,
    sellingType: "Purchase",
    price: 1500,
    contactLink: "https://docs.google.com/",
    isVisibleToClients: true,
    tag: ["tech"],
    image: "/images/products/camera.png",
    createdAt: "2025-07-15T10:00:00Z",
  },
  {
    id: "inv004",
    name: "RFL Chair",
    brand: "RFL",
    category: "Furniture",
    serialNumber: "CHAIR-004",
    location: "Storage Room",
    status: "Checked Out",
    stock: 9,
    checkedOutBy: "alex root",
    sellingType: "rent",
    price: 150,
    contactLink: "https://docs.google.com/",
    isVisibleToClients: true,
    tag: ["plastic"],
    image: "/images/products/chair.png",
    createdAt: "2025-07-15T10:00:00Z",
  },
  {
    id: "inv005",
    name: "iPad Pro",
    brand: "Apple",
    category: "Tablet",
    serialNumber: "IPAD-005",
    location: "Head Office",
    status: "Checked Out",
    stock: 4,
    checkedOutBy: "ross taylor",
    sellingType: "Purchase",
    price: 1200,
    contactLink: "https://docs.google.com/",
    isVisibleToClients: true,
    tag: ["tech"],
    image: "/images/products/ipad.png",
    createdAt: "2025-07-15T10:00:00Z",
  },
  {
    id: "inv006",
    name: "Speaker",
    brand: "BRB",
    category: "Audio",
    serialNumber: "SPKR-006",
    location: "Audio Lab",
    status: "Checked Out",
    stock: 4,
    checkedOutBy: "alan oki",
    sellingType: "purchase",
    price: 1200,
    contactLink: "https://docs.google.com/",
    isVisibleToClients: true,
    tag: ["tech"],
    image: "/images/products/speaker.png",
    createdAt: "2025-07-15T10:00:00Z",
  },
  {
    id: "inv007",
    name: "CC Camera",
    brand: "BRB",
    category: "Security",
    serialNumber: "CCC-007",
    location: "Conference Room",
    status: "Checked Out",
    stock: 20,
    checkedOutBy: "ali asgar",
    sellingType: "purchase",
    price: 500,
    contactLink: "https://docs.google.com/",
    isVisibleToClients: true,
    tag: ["tech"],
    image: "/images/products/cccamera.png",
    createdAt: "2025-07-15T10:00:00Z",
  },
  {
    id: "inv008",
    name: "Tronix UPS",
    brand: "Tronix",
    category: "Power Supply",
    serialNumber: "UPS-008",
    location: "Storage Room",
    status: "Checked Out",
    stock: 14,
    checkedOutBy: "md masum",
    sellingType: "rent",
    price: 1000,
    contactLink: "https://docs.google.com/",
    isVisibleToClients: true,
    tag: ["tech"],
    image: "/images/products/ups.png",
    createdAt: "2025-07-15T10:00:00Z",
  },
  {
    id: "inv009",
    name: "Tronix IPS",
    brand: "Tronix",
    category: "Power Supply",
    serialNumber: "IPS-009",
    location: "Storage Room",
    status: "Checked Out",
    stock: 51,
    checkedOutBy: "mohammad ali",
    sellingType: "rent",
    price: 1200,
    contactLink: "https://docs.google.com/",
    isVisibleToClients: true,
    tag: ["tech"],
    image: "/images/products/ips.png",
    createdAt: "2025-07-15T10:00:00Z",
  },
];
