export const passwordsList = [
  {
    id: 1,
    company: "wifi",
    username: "user@wifi.com",
    password: "user123456",
    logo: "/images/company/wifi.png",
    access: ["AD"],
  },
  {
    id: 2,
    company: "LG",
    username: "lgit@company.com",
    password: "lg123456",
    logo: "/images/company/lg.png",
    access: ["AD"],
  },
  {
    id: 3,
    company: "Google",
    username: "google.com",
    password: "google123",
    logo: "/images/company/google.png",
    access: ["LM", "JG", "SD", "AC"],
  },
  {
    id: 15,
    company: "Slack",
    username: "luuki@.mail",
    password: "user123456",
    logo: "/images/company/slack.png",
    access: ["LM", "JG"],
  },
  {
    id: 5,
    company: "AWS",
    username: "aws.com",
    password: "user123456",
    logo: "/images/company/aws.png",
    access: ["LM", "JG", "SD"],
  },
  {
    id: 6,
    company: "Zoom",
    username: "zoom.com",
    password: "user123456",
    logo: "/images/company/zoom.png",
    access: ["LM", "JG"],
  },
  {
    id: 7,
    company: "Zoom",
    username: "zoom.com",
    password: "user123456",
    logo: "/images/company/zoom.png",
    access: ["LM", "JG"],
  },
  {
    id: 8,
    company: "Zoom",
    username: "zoom.com",
    password: "user123456",
    logo: "/images/company/zoom.png",
    access: ["LM", "JG"],
  },
  {
    id: 9,
    company: "Zoom",
    username: "zoom.com",
    password: "user123456",
    logo: "/images/company/zoom.png",
    access: ["LM", "JG"],
  },
  {
    id: 10,
    company: "Zoom",
    username: "zoom.com",
    password: "user123456",
    logo: "/images/company/zoom.png",
    access: ["LM", "JG"],
  },
  {
    id: 11,
    company: "Zoom",
    username: "zoom.com",
    password: "user123456",
    logo: "/images/company/zoom.png",
    access: ["LM", "JG"],
  },
  {
    id: 12,
    company: "Zoom",
    username: "zoom.com",
    password: "user123456",
    logo: "/images/company/zoom.png",
    access: ["LM", "JG"],
  },
  {
    id: 13,
    company: "Zoom",
    username: "zoom.com",
    password: "user123456",
    logo: "/images/company/zoom.png",
    access: ["LM", "JG"],
  },
  {
    id: 14,
    company: "Zoom",
    username: "zoom.com",
    password: "user123456",
    logo: "/images/company/zoom.png",
    access: ["LM", "JG"],
  },
];
