export const product_list = [
  {
    id: 1,
    name: "macBook pro",
    image: "/images/products/laptop.png",
    price: "$1200",
    location: "new york",
    person_assigned: "john doe",
    brand: "apple",
    selling_type: "rent",
    status: "active",
    tag: ["tech"],
  },
  {
    id: 2,
    name: "projector",
    image: "/images/products/projector.png",
    price: "$600",
    location: "virginia",
    person_assigned: "alex root",
    brand: "asus",
    selling_type: "rent",
    status: "active",
    tag: ["tech"],
  },
  {
    id: 3,
    name: "sony camera",
    image: "/images/products/camera.png",
    price: "$1500",
    location: "florida",
    person_assigned: "l messi",
    brand: "sony",
    selling_type: "rent",
    status: "active",
    tag: ["tech"],
  },
  {
    id: 4,
    name: "Lapto Chair",
    image: "/images/products/chair.png",
    price: "$150",
    location: "Mississippi",
    person_assigned: "alex root",
    brand: "RFL",
    selling_type: "purchase",
    status: "active",
    tag: ["plastic"],
  },
  {
    id: 5,
    name: "iPad Pro",
    image: "/images/products/ipad.png",
    price: "$1,200",
    location: "Texas",
    person_assigned: "ross taylor",
    brand: "apple",
    selling_type: "rent",
    status: "active",
    tag: ["tech"],
  },
  {
    id: 6,
    name: "Speaker",
    image: "/images/products/speaker.png",
    price: "$1,200",
    location: "California",
    person_assigned: "alan oki",
    brand: "brb",
    selling_type: "purchase",
    status: "active",
    tag: ["tech"],
  },
  {
    id: 7,
    name: "CC Camera",
    image: "/images/products/cccamera.png",
    price: "$500",
    location: "Florida",
    person_assigned: "ali asgar",
    brand: "brb",
    selling_type: "purchase",
    status: "active",
    tag: ["tech"],
  },
  {
    id: 8,
    name: "Tronix Ups",
    image: "/images/products/ups.png",
    price: "$1000",
    location: "California",
    person_assigned: "md masum",
    brand: "tronix",
    selling_type: "rent",
    status: "active",
    tag: ["tech"],
  },
  {
    id: 9,
    name: "Tronix Ips",
    image: "/images/products/ips.png",
    price: "$1,200",
    location: "Texas",
    person_assigned: "mohammad ali",
    brand: "tronix",
    selling_type: "rent",
    status: "active",
    tag: ["tech"],
  },
];
